# PANDAS LAB - Continuation of the EuroLeague Case Study
## Let's compare the competitions!

![](https://eurospects.com/wp-content/uploads/2018/10/eurocupeuroleague.png)

First of all, we must 

- Import the actual.csv Dataset. This dataset will be the CSV of the result obtained in class.
- Import ec23.xlsx. This dataset correspond to the import the dataset corresponding to Eurocup. Don't worry, this time the Excel will be cleaned (almost)

<details>
    <summary> Lab results </summary>

![](https://media1.tenor.com/m/lx2WSGRk8bcAAAAC/pulp-fiction-john-travolta.gif)

PERO QUÉ OS HABÉIS CREÍDO

</details>

In [1]:
#pip install openpyxl
# In case there is an error with this .xlsx document opening, install this library

In [5]:
import pandas as pd
import numpy as np

In [6]:
elteams=pd.read_csv("datasets/actual.csv")
ecteams=pd.read_excel("datasets/ec2023.xlsx", index_col=False)

Let's analyze the EuroCup Dataframe! Is there any cleaning needed? Remember the basics: 
- Drop Null Values
- Drop Duplicate Rows
- Drop Strange Columns if you see any

In [7]:
# Your Code here: 
ecteams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  173 non-null    int64
 1   fecha       173 non-null    object
 2   ronda       173 non-null    int64
 3   local       173 non-null    object
 4   visitante   173 non-null    object
 5   localscore  173 non-null    int64
 6   roadscore   172 non-null    float64
 7   Winner      173 non-null    object
 8   Ganador     172 non-null    float64
 9   plusminus   172 non-null    float64
dtypes: float64(3), int64(3), object(4)
memory usage: 13.6+ KB

In [8]:
elteams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225 entries, 0 to 224
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Competition  225 non-null    object
 1   Phase        225 non-null    object
 2   Ronda        225 non-null    int64
 3   Dia          225 non-null    object
 4   Hora         225 non-null    object
 5   Local        225 non-null    object
 6   Visitante    225 non-null    object
 7   Localscore   225 non-null    int64
 8   Roadscore    225 non-null    int64
 9   Arbitros     225 non-null    object
 10  Plusminus    225 non-null    int64
 11  Winner       225 non-null    object
 12  Ganador      225 non-null    object
dtypes: int64(4), object(9)
memory usage: 23.0+ KB

Let's now compare it with the EL dataset that we have: You might select a sample of both of them and see what are the inconsistencies!

In [9]:
#Your sample ecteams code here: 
ecteams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  173 non-null    int64
 1   fecha       173 non-null    object
 2   ronda       173 non-null    int64
 3   local       173 non-null    object
 4   visitante   173 non-null    object
 5   localscore  173 non-null    int64
 6   roadscore   172 non-null    float64
 7   Winner      173 non-null    object
 8   Ganador     172 non-null    float64
 9   plusminus   172 non-null    float64
dtypes: float64(3), int64(3), object(4)
memory usage: 13.6+ KB

In [10]:
ecteams.head()

,Unnamed: 0,fecha,ronda,local,visitante,localscore,roadscore,Winner,Ganador,plusminus
0,0,2024-01-31T21:00:00,17,Dreamland Gran Canaria,U-BT Cluj-Napoca,111,113.0,Visitante,113.0,-2.0
1,1,2024-01-31T20:00:00,17,Dolomiti Energia Trento,Buducnost VOLI Podgorica,78,97.0,Visitante,97.0,-19.0
2,2,2024-01-31T19:30:00,17,ratiopharm Ulm,Aris Midea Thessaloniki,66,86.0,Visitante,86.0,-20.0
3,3,2024-01-31T18:30:00,17,Cedevita Olimpija Ljubljana,London Lions,85,92.0,Visitante,92.0,-7.0
4,4,2024-01-31T18:00:00,17,Turk Telekom Ankara,Mincidelice JL Bourg en Bresse,64,68.0,Visitante,68.0,-4.0

In [11]:
#Your sample elteams code here: 
elteams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225 entries, 0 to 224
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Competition  225 non-null    object
 1   Phase        225 non-null    object
 2   Ronda        225 non-null    int64
 3   Dia          225 non-null    object
 4   Hora         225 non-null    object
 5   Local        225 non-null    object
 6   Visitante    225 non-null    object
 7   Localscore   225 non-null    int64
 8   Roadscore    225 non-null    int64
 9   Arbitros     225 non-null    object
 10  Plusminus    225 non-null    int64
 11  Winner       225 non-null    object
 12  Ganador      225 non-null    object
dtypes: int64(4), object(9)
memory usage: 23.0+ KB

In [12]:
elteams.head()

,Competition,Phase,Ronda,Dia,Hora,Local,Visitante,Localscore,Roadscore,Arbitros,Plusminus,Winner,Ganador
0,Euroleague,Regular Season,1,2023-10-05,19:00:00,Crvena Zvezda Meridianbet Belgrade,LDLC ASVEL Villeurbanne,94,73,"['ROCHA, FERNANDO', 'PATERNICO, CARMELO', 'PAS...",21,Crvena Zvezda Meridianbet Belgrade,Local
1,Euroleague,Regular Season,1,2023-10-05,20:05:00,Maccabi Playtika Tel Aviv,Partizan Mozzart Bet Belgrade,96,81,"['PEREZ, MIGUEL ANGEL', 'VILIUS, GYTIS', 'KARD...",15,Maccabi Playtika Tel Aviv,Local
2,Euroleague,Regular Season,1,2023-10-05,20:30:00,Virtus Segafredo Bologna,Zalgiris Kaunas,79,82,"['BOLTAUZER, MATEJ', 'PANTHER, ANNE', 'SILVA, ...",-3,Zalgiris Kaunas,Visitante
3,Euroleague,Regular Season,1,2023-10-05,20:30:00,FC Bayern Munich,ALBA Berlin,80,68,"['GARCIA, JUAN CARLOS', 'LATISEVS, OLEGS', 'SU...",12,FC Bayern Munich,Local
4,Euroleague,Regular Season,1,2023-10-05,20:30:00,FC Barcelona,Anadolu Efes Istanbul,91,74,"['RADOVIC, SRETEN', 'DIFALLAH, MEHDI', 'JOVCIC...",17,FC Barcelona,Local

What are the inconsistencies that you are seeing? Write them down!

- Hay columnas en elteams que no existen en ecteams, como por ejemplo la de árbitros.
- Las columnas en elteams están en mayúsculas y todas, en ecteams solo dos. Tendremos que tener cuidado.
- En ecteams tenemos fecha como única columna y en el teams esta dividida en dos.
- La columna winner en ecteams nos ofrece si el ganador ha sido el visitante o el local, por contra en la columnna winner de elteams nos ofrece el nombre del equipo ganador.

<details>
    <summary> Expand the box to see the inconsistencies </summary>

- The columns are named in lowercase and the columns in Euroleague are capitalized
- There are some missing columns (f.e. Arbitros)
- Fecha is not split in Dia and Hora
- `Winner and Ganador Columns show different data` are not the same! Be extremely careful about it

</details>

As you can see there are a lot of different inconsistencies right? 
But beofore starting cleaning like crazy people, let's take a second to know what do we want to compare: 

- The CLUBS are impossible to compare, as different competitions defines different clubs
- Both rounds (Eurocup has less rounds) and Dates (Different Dates) are also not really useful
- We don't have information about Arbitros

## Conclusion

### We must take into consideration what data we DO have in both dataframes to compare it propperly and don't use time cleaning unnecessary things. 

In this particular case, we will need to compare:

`Competition`: The main column that define one from another. 

Create the Competition column in the EuroCup dataframe, being the fixed value "Eurocup"

In [13]:
#Your Code here: 
ecteams["Competition"] = "Eurocup"
ecteams

,Unnamed: 0,fecha,ronda,local,visitante,localscore,roadscore,Winner,Ganador,plusminus,Competition
0,0,2024-01-31T21:00:00,17,Dreamland Gran Canaria,U-BT Cluj-Napoca,111,113.0,Visitante,113.0,-2.0,Eurocup
1,1,2024-01-31T20:00:00,17,Dolomiti Energia Trento,Buducnost VOLI Podgorica,78,97.0,Visitante,97.0,-19.0,Eurocup
2,2,2024-01-31T19:30:00,17,ratiopharm Ulm,Aris Midea Thessaloniki,66,86.0,Visitante,86.0,-20.0,Eurocup
3,3,2024-01-31T18:30:00,17,Cedevita Olimpija Ljubljana,London Lions,85,92.0,Visitante,92.0,-7.0,Eurocup
4,4,2024-01-31T18:00:00,17,Turk Telekom Ankara,Mincidelice JL Bourg en Bresse,64,68.0,Visitante,68.0,-4.0,Eurocup
...,...,...,...,...,...,...,...,...,...,...,...
168,165,2023-10-04T18:00:00,1,U-BT Cluj-Napoca,Turk Telekom Ankara,80,71.0,Local,80.0,9.0,Eurocup
169,166,2023-10-04T18:00:00,1,Prometey Slobozhanske,Veolia Towers Hamburg,97,77.0,Local,97.0,20.0,Eurocup
170,167,2023-10-03T20:30:00,1,Paris Basketball,Wolves Vilnius,105,78.0,Local,105.0,27.0,Eurocup
171,168,2023-10-03T19:30:00,1,ratiopharm Ulm,Dolomiti Energia Trento,80,70.0,Local,80.0,10.0,Eurocup
172,169,2023-10-03T19:00:00,1,Hapoel Shlomo Tel Aviv,Cedevita Olimpija Ljubljana,100,73.0,Local,100.0,27.0,Eurocup

`Ganador`: Being the actual values "Local" or "Visitante"

**BE CAREFUL**: Before changing the correct column to "Ganador" from the EC dataframe, there is a "Ganador" column with the incorrect information: STEP BY STEP!

In [14]:
#Drop the Column Ganador from the Eurocup Dataframe
ecteams = ecteams.drop("Ganador" , axis=1)
ecteams

,Unnamed: 0,fecha,ronda,local,visitante,localscore,roadscore,Winner,plusminus,Competition
0,0,2024-01-31T21:00:00,17,Dreamland Gran Canaria,U-BT Cluj-Napoca,111,113.0,Visitante,-2.0,Eurocup
1,1,2024-01-31T20:00:00,17,Dolomiti Energia Trento,Buducnost VOLI Podgorica,78,97.0,Visitante,-19.0,Eurocup
2,2,2024-01-31T19:30:00,17,ratiopharm Ulm,Aris Midea Thessaloniki,66,86.0,Visitante,-20.0,Eurocup
3,3,2024-01-31T18:30:00,17,Cedevita Olimpija Ljubljana,London Lions,85,92.0,Visitante,-7.0,Eurocup
4,4,2024-01-31T18:00:00,17,Turk Telekom Ankara,Mincidelice JL Bourg en Bresse,64,68.0,Visitante,-4.0,Eurocup
...,...,...,...,...,...,...,...,...,...,...
168,165,2023-10-04T18:00:00,1,U-BT Cluj-Napoca,Turk Telekom Ankara,80,71.0,Local,9.0,Eurocup
169,166,2023-10-04T18:00:00,1,Prometey Slobozhanske,Veolia Towers Hamburg,97,77.0,Local,20.0,Eurocup
170,167,2023-10-03T20:30:00,1,Paris Basketball,Wolves Vilnius,105,78.0,Local,27.0,Eurocup
171,168,2023-10-03T19:30:00,1,ratiopharm Ulm,Dolomiti Energia Trento,80,70.0,Local,10.0,Eurocup
172,169,2023-10-03T19:00:00,1,Hapoel Shlomo Tel Aviv,Cedevita Olimpija Ljubljana,100,73.0,Local,27.0,Eurocup

In [15]:
#Rename the column with the actual information to "Ganador"
ecteams = ecteams.rename (columns={"Winner" : "Ganador"})
ecteams

,Unnamed: 0,fecha,ronda,local,visitante,localscore,roadscore,Ganador,plusminus,Competition
0,0,2024-01-31T21:00:00,17,Dreamland Gran Canaria,U-BT Cluj-Napoca,111,113.0,Visitante,-2.0,Eurocup
1,1,2024-01-31T20:00:00,17,Dolomiti Energia Trento,Buducnost VOLI Podgorica,78,97.0,Visitante,-19.0,Eurocup
2,2,2024-01-31T19:30:00,17,ratiopharm Ulm,Aris Midea Thessaloniki,66,86.0,Visitante,-20.0,Eurocup
3,3,2024-01-31T18:30:00,17,Cedevita Olimpija Ljubljana,London Lions,85,92.0,Visitante,-7.0,Eurocup
4,4,2024-01-31T18:00:00,17,Turk Telekom Ankara,Mincidelice JL Bourg en Bresse,64,68.0,Visitante,-4.0,Eurocup
...,...,...,...,...,...,...,...,...,...,...
168,165,2023-10-04T18:00:00,1,U-BT Cluj-Napoca,Turk Telekom Ankara,80,71.0,Local,9.0,Eurocup
169,166,2023-10-04T18:00:00,1,Prometey Slobozhanske,Veolia Towers Hamburg,97,77.0,Local,20.0,Eurocup
170,167,2023-10-03T20:30:00,1,Paris Basketball,Wolves Vilnius,105,78.0,Local,27.0,Eurocup
171,168,2023-10-03T19:30:00,1,ratiopharm Ulm,Dolomiti Energia Trento,80,70.0,Local,10.0,Eurocup
172,169,2023-10-03T19:00:00,1,Hapoel Shlomo Tel Aviv,Cedevita Olimpija Ljubljana,100,73.0,Local,27.0,Eurocup

As seen in the first look at the dataframes, there was a problem with the columns: Are lower when they should be Capitalized, as in the Euroleague DataFrame. Change the column names to capitalize. 

is there a quick way to do it?

In [16]:
# Your code here: 
ecteams = ecteams.rename(columns=lambda x: x.capitalize())
ecteams

,Unnamed: 0,Fecha,Ronda,Local,Visitante,Localscore,Roadscore,Ganador,Plusminus,Competition
0,0,2024-01-31T21:00:00,17,Dreamland Gran Canaria,U-BT Cluj-Napoca,111,113.0,Visitante,-2.0,Eurocup
1,1,2024-01-31T20:00:00,17,Dolomiti Energia Trento,Buducnost VOLI Podgorica,78,97.0,Visitante,-19.0,Eurocup
2,2,2024-01-31T19:30:00,17,ratiopharm Ulm,Aris Midea Thessaloniki,66,86.0,Visitante,-20.0,Eurocup
3,3,2024-01-31T18:30:00,17,Cedevita Olimpija Ljubljana,London Lions,85,92.0,Visitante,-7.0,Eurocup
4,4,2024-01-31T18:00:00,17,Turk Telekom Ankara,Mincidelice JL Bourg en Bresse,64,68.0,Visitante,-4.0,Eurocup
...,...,...,...,...,...,...,...,...,...,...
168,165,2023-10-04T18:00:00,1,U-BT Cluj-Napoca,Turk Telekom Ankara,80,71.0,Local,9.0,Eurocup
169,166,2023-10-04T18:00:00,1,Prometey Slobozhanske,Veolia Towers Hamburg,97,77.0,Local,20.0,Eurocup
170,167,2023-10-03T20:30:00,1,Paris Basketball,Wolves Vilnius,105,78.0,Local,27.0,Eurocup
171,168,2023-10-03T19:30:00,1,ratiopharm Ulm,Dolomiti Energia Trento,80,70.0,Local,10.0,Eurocup
172,169,2023-10-03T19:00:00,1,Hapoel Shlomo Tel Aviv,Cedevita Olimpija Ljubljana,100,73.0,Local,27.0,Eurocup

Now it is time to just take the useful columns from each data! We will call the result subsets `comp_el` and `comp_ec`

REMEMBER: Use the same order of the columns for each dataset. 

Recommended order: Competition, Localscore, Roadscore, Plusminus, Ganador. **Nothing else is useful**

In [17]:
# Your code here: 
comp_el = elteams[["Competition", "Localscore", "Roadscore", "Plusminus", "Ganador"]]
comp_el

    Competition  Localscore  Roadscore  Plusminus    Ganador
0    Euroleague          94         73         21      Local
1    Euroleague          96         81         15      Local
2    Euroleague          79         82         -3  Visitante
3    Euroleague          80         68         12      Local
4    Euroleague          91         74         17      Local
..          ...         ...        ...        ...        ...
220  Euroleague          79         73          6      Local
221  Euroleague          80         68         12      Local
222  Euroleague          76         85         -9  Visitante
223  Euroleague          88         84          4      Local
224  Euroleague          76         69          7      Local

[225 rows x 5 columns]

In [18]:
comp_ec = ecteams[["Competition", "Localscore", "Roadscore", "Plusminus", "Ganador"]]
comp_ec

    Competition  Localscore  Roadscore  Plusminus    Ganador
0       Eurocup         111      113.0       -2.0  Visitante
1       Eurocup          78       97.0      -19.0  Visitante
2       Eurocup          66       86.0      -20.0  Visitante
3       Eurocup          85       92.0       -7.0  Visitante
4       Eurocup          64       68.0       -4.0  Visitante
..          ...         ...        ...        ...        ...
168     Eurocup          80       71.0        9.0      Local
169     Eurocup          97       77.0       20.0      Local
170     Eurocup         105       78.0       27.0      Local
171     Eurocup          80       70.0       10.0      Local
172     Eurocup         100       73.0       27.0      Local

[173 rows x 5 columns]

Time to concatenate them both! Create a concat of both Dfs, called `competition`

In [19]:
# Your code here:
competition=pd.concat([comp_el, comp_ec], axis=0, ignore_index=True)
competition

    Competition  Localscore  Roadscore  Plusminus    Ganador
0    Euroleague          94       73.0       21.0      Local
1    Euroleague          96       81.0       15.0      Local
2    Euroleague          79       82.0       -3.0  Visitante
3    Euroleague          80       68.0       12.0      Local
4    Euroleague          91       74.0       17.0      Local
..          ...         ...        ...        ...        ...
393     Eurocup          80       71.0        9.0      Local
394     Eurocup          97       77.0       20.0      Local
395     Eurocup         105       78.0       27.0      Local
396     Eurocup          80       70.0       10.0      Local
397     Eurocup         100       73.0       27.0      Local

[398 rows x 5 columns]

## Well done!

Now we have the combination of both competitions in the same dataframe. Is time for the questions you must answer:

1. How many matches have been in each competition?
2. What are the maximum points that a local team has scored per competition? And the road team as well. 
3. Do the same operations with the average points (per competition)
4. Can you tell me the maximum difference that has been in a match, splitted by competition? 
    - Careful: The Plusminus is both positive and negative, being negative that the Road Team has achieved the Victory. To have the absolute, create a new Column named Absolut_Plusminus. Remember: np.where is life!
5. Also grouped by competition, give me the number of victories of the Locals and the Visitors

In [20]:
# 1
número_partidos_competición = competition["Competition"].value_counts()
print("El número de partidos por competición es:" , número_partidos_competición)

El número de partidos por competición es: Competition
Euroleague    225
Eurocup       173
Name: count, dtype: int64

In [21]:
# 2
maxima_puntuacion_local = competition.groupby("Competition")["Localscore"].max()
print("La máxima puntuación del equipo local por competición es:" , maxima_puntuacion_local)

La máxima puntuación del equipo local por competición es: Competition
Eurocup       120
Euroleague    130
Name: Localscore, dtype: int64

In [22]:
maxima_puntuacion_visitante = competition.groupby("Competition")["Roadscore"].max()
print("La máxima puntuación del equipo visitante por competición es:" , maxima_puntuacion_visitante)

La máxima puntuación del equipo visitante por competición es: Competition
Eurocup       114.0
Euroleague    126.0
Name: Roadscore, dtype: float64

In [23]:
# 3
puntuacion_media = competition.groupby("Competition")["Localscore"].mean()
print("La puntuación media por competición es:" , puntuacion_media)

La puntuación media por competición es: Competition
Eurocup       85.150289
Euroleague    83.284444
Name: Localscore, dtype: float64

In [24]:
# 4 Creamos una nueva columna que se llama Absolut_Plusminus que nos indicara el valor abosluto de Plusminus
competition["Absolut_Plusminus"] = abs(competition["Plusminus"])
competition

,Competition,Localscore,Roadscore,Plusminus,Ganador,Absolut_Plusminus
0,Euroleague,94,73.0,21.0,Local,21.0
1,Euroleague,96,81.0,15.0,Local,15.0
2,Euroleague,79,82.0,-3.0,Visitante,3.0
3,Euroleague,80,68.0,12.0,Local,12.0
4,Euroleague,91,74.0,17.0,Local,17.0
...,...,...,...,...,...,...
393,Eurocup,80,71.0,9.0,Local,9.0
394,Eurocup,97,77.0,20.0,Local,20.0
395,Eurocup,105,78.0,27.0,Local,27.0
396,Eurocup,80,70.0,10.0,Local,10.0
397,Eurocup,100,73.0,27.0,Local,27.0

In [25]:
máxima_diferencia = competition.groupby("Competition")["Absolut_Plusminus"].max()
print("El número de partidos por competición es:" , máxima_diferencia)

El número de partidos por competición es: Competition
Eurocup       39.0
Euroleague    39.0
Name: Absolut_Plusminus, dtype: float64

In [26]:
# 5
victorias_locales_visitantes_por_competición = competition.groupby(["Competition","Ganador"])["Ganador"].count()
print("El número de victorias por competición es:" , victorias_locales_visitantes_por_competición)

El número de victorias por competición es: Competition  Ganador
Eurocup      Local         91
             Visitante     82
Euroleague   Local        150
             Visitante     75
Name: Ganador, dtype: int64